version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: quantum_postgres
    environment:
      POSTGRES_DB: quantum
      POSTGRES_USER: quantum
      POSTGRES_PASSWORD: quantum1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: quantum_redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    container_name: quantum_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: quantum_zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

volumes:
  pgdata: