// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: forwarder/forwarder.proto

package forwarder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterChannelSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Subscriber    string                 `protobuf:"bytes,3,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChannelSessionRequest) Reset() {
	*x = RegisterChannelSessionRequest{}
	mi := &file_forwarder_forwarder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChannelSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChannelSessionRequest) ProtoMessage() {}

func (x *RegisterChannelSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_forwarder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChannelSessionRequest.ProtoReflect.Descriptor instead.
func (*RegisterChannelSessionRequest) Descriptor() ([]byte, []int) {
	return file_forwarder_forwarder_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterChannelSessionRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *RegisterChannelSessionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterChannelSessionRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

type RegisterChannelSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChannelSessionResponse) Reset() {
	*x = RegisterChannelSessionResponse{}
	mi := &file_forwarder_forwarder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChannelSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChannelSessionResponse) ProtoMessage() {}

func (x *RegisterChannelSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_forwarder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChannelSessionResponse.ProtoReflect.Descriptor instead.
func (*RegisterChannelSessionResponse) Descriptor() ([]byte, []int) {
	return file_forwarder_forwarder_proto_rawDescGZIP(), []int{1}
}

type RemoveChannelSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChannelSessionRequest) Reset() {
	*x = RemoveChannelSessionRequest{}
	mi := &file_forwarder_forwarder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChannelSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChannelSessionRequest) ProtoMessage() {}

func (x *RemoveChannelSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_forwarder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChannelSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveChannelSessionRequest) Descriptor() ([]byte, []int) {
	return file_forwarder_forwarder_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveChannelSessionRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *RemoveChannelSessionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveChannelSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChannelSessionResponse) Reset() {
	*x = RemoveChannelSessionResponse{}
	mi := &file_forwarder_forwarder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChannelSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChannelSessionResponse) ProtoMessage() {}

func (x *RemoveChannelSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_forwarder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChannelSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveChannelSessionResponse) Descriptor() ([]byte, []int) {
	return file_forwarder_forwarder_proto_rawDescGZIP(), []int{3}
}

var File_forwarder_forwarder_proto protoreflect.FileDescriptor

const file_forwarder_forwarder_proto_rawDesc = "" +
	"\n" +
	"\x19forwarder/forwarder.proto\x12\tforwarder\"w\n" +
	"\x1dRegisterChannelSessionRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x03 \x01(\tR\n" +
	"subscriber\" \n" +
	"\x1eRegisterChannelSessionResponse\"U\n" +
	"\x1bRemoveChannelSessionRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x1e\n" +
	"\x1cRemoveChannelSessionResponse2\xec\x01\n" +
	"\x0eForwardService\x12o\n" +
	"\x16RegisterChannelSession\x12(.forwarder.RegisterChannelSessionRequest\x1a).forwarder.RegisterChannelSessionResponse\"\x00\x12i\n" +
	"\x14RemoveChannelSession\x12&.forwarder.RemoveChannelSessionRequest\x1a'.forwarder.RemoveChannelSessionResponse\"\x00B\x17Z\x15./forwarder;forwarderb\x06proto3"

var (
	file_forwarder_forwarder_proto_rawDescOnce sync.Once
	file_forwarder_forwarder_proto_rawDescData []byte
)

func file_forwarder_forwarder_proto_rawDescGZIP() []byte {
	file_forwarder_forwarder_proto_rawDescOnce.Do(func() {
		file_forwarder_forwarder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forwarder_forwarder_proto_rawDesc), len(file_forwarder_forwarder_proto_rawDesc)))
	})
	return file_forwarder_forwarder_proto_rawDescData
}

var file_forwarder_forwarder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_forwarder_forwarder_proto_goTypes = []any{
	(*RegisterChannelSessionRequest)(nil),  // 0: forwarder.RegisterChannelSessionRequest
	(*RegisterChannelSessionResponse)(nil), // 1: forwarder.RegisterChannelSessionResponse
	(*RemoveChannelSessionRequest)(nil),    // 2: forwarder.RemoveChannelSessionRequest
	(*RemoveChannelSessionResponse)(nil),   // 3: forwarder.RemoveChannelSessionResponse
}
var file_forwarder_forwarder_proto_depIdxs = []int32{
	0, // 0: forwarder.ForwardService.RegisterChannelSession:input_type -> forwarder.RegisterChannelSessionRequest
	2, // 1: forwarder.ForwardService.RemoveChannelSession:input_type -> forwarder.RemoveChannelSessionRequest
	1, // 2: forwarder.ForwardService.RegisterChannelSession:output_type -> forwarder.RegisterChannelSessionResponse
	3, // 3: forwarder.ForwardService.RemoveChannelSession:output_type -> forwarder.RemoveChannelSessionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forwarder_forwarder_proto_init() }
func file_forwarder_forwarder_proto_init() {
	if File_forwarder_forwarder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forwarder_forwarder_proto_rawDesc), len(file_forwarder_forwarder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forwarder_forwarder_proto_goTypes,
		DependencyIndexes: file_forwarder_forwarder_proto_depIdxs,
		MessageInfos:      file_forwarder_forwarder_proto_msgTypes,
	}.Build()
	File_forwarder_forwarder_proto = out.File
	file_forwarder_forwarder_proto_goTypes = nil
	file_forwarder_forwarder_proto_depIdxs = nil
}
