// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: chat/user.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_chat_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_chat_user_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *AddUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_chat_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_chat_user_proto_rawDescGZIP(), []int{1}
}

var File_chat_user_proto protoreflect.FileDescriptor

const file_chat_user_proto_rawDesc = "" +
	"\n" +
	"\x0fchat/user.proto\x12\x04chat\"H\n" +
	"\x0eAddUserRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x11\n" +
	"\x0fAddUserResponse2P\n" +
	"\vUserService\x12A\n" +
	"\x10AddUserToChannel\x12\x14.chat.AddUserRequest\x1a\x15.chat.AddUserResponse\"\x00B\rZ\v./chat;chatb\x06proto3"

var (
	file_chat_user_proto_rawDescOnce sync.Once
	file_chat_user_proto_rawDescData []byte
)

func file_chat_user_proto_rawDescGZIP() []byte {
	file_chat_user_proto_rawDescOnce.Do(func() {
		file_chat_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_user_proto_rawDesc), len(file_chat_user_proto_rawDesc)))
	})
	return file_chat_user_proto_rawDescData
}

var file_chat_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_user_proto_goTypes = []any{
	(*AddUserRequest)(nil),  // 0: chat.AddUserRequest
	(*AddUserResponse)(nil), // 1: chat.AddUserResponse
}
var file_chat_user_proto_depIdxs = []int32{
	0, // 0: chat.UserService.AddUserToChannel:input_type -> chat.AddUserRequest
	1, // 1: chat.UserService.AddUserToChannel:output_type -> chat.AddUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_user_proto_init() }
func file_chat_user_proto_init() {
	if File_chat_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_user_proto_rawDesc), len(file_chat_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_user_proto_goTypes,
		DependencyIndexes: file_chat_user_proto_depIdxs,
		MessageInfos:      file_chat_user_proto_msgTypes,
	}.Build()
	File_chat_user_proto = out.File
	file_chat_user_proto_goTypes = nil
	file_chat_user_proto_depIdxs = nil
}
