runmode: debug               
addr: :8080   
shutdown-timeout: 10s 
 
db:
   host: 127.0.0.1 
   port: 5432       
   username: quantum  
   password: quantum1234 
   database: quantum  
   sslmode: disable 
   max-idle-connections: 100 
   max-open-connections: 100 
   max-connection-life-time: 10s
   log-level: 4 

redis:
  host: 127.0.0.1
  port: 6379
  username: ""
  password: ""
  db: 0
  max-idle-connections: 10
  max-open-connections: 100
  max-connection-life-time: 10s
  read-timeout: 3s
  write-timeout: 3s
  pool-timeout: 5s
  min-idle-connections: 2
  dial-timeout: 5s
  enable-cluster: false