runmode: debug               
addr: :8080   
shutdown-timeout: 10s 

jwt:
   secret: m35xbjk4LXlobmctczNjcjN0LWszeTY2NiQ=
   timeout: 24h
   max-refresh: 168h
 
db:
   host: 127.0.0.1 
   port: 5432       
   username: quantum  
   password: quantum1234 
   database: quantum  
   sslmode: disable 
   max-idle-connections: 100 
   max-open-connections: 100 
   max-connection-life-time: 10s
   log-level: 4 

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  poll: 15
  conn: 10

mail:
  driver: 'smtp'
  host: 'smtp.gmail.com'
  name: 'yourname@gmail.com'
  password: 'your_gmail_app_password'
  port: 465
  encryption: 'ssl'
  fromName: 'Im-Services'

kafka:
  addr: 
    - 127.0.0.1:9092